spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oneMind?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: oneMind
    password: oneMind!@

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 611816338810-a1i3r7jtvp4tp794n11gbth90bgqojn5.apps.googleusercontent.com
            client-secret: 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
        provider:
          google:
            token-info: https://oauth2.googleapis.com/tokeninfo
  cache:
    type: redis

  redis:
    port: 6379
    host: localhost

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: true
#    hibernate:
#      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true


application:
  jwt:
    secretKey: ZXlKaGJHY2lPaUpJVXpVeE1pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRZNU9UVXpNelUzTnl3aWFXRjBJam94TmprNU5UTXpOVGMzZlEuUGRBWUxzbXpxUUR2OU5sb3NrMm5EY1lrNlVqMjE5ek9HRkhBYTN3NDh5ZlZ0OGQtZUVaV29iSy03R1htUE53bWNRcDJMZW1TY0lES244YXd5UnFsVXc=
    expiration: 900000
    refreshExpiration: 999999

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha

server:
  port: 8080
  address: 192.168.0.22





